In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r"C:\Users\HomePC\Desktop\Week 8 AnalystLab\WDICSV.csv")

In [4]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.685118,19.205632,19.742772,20.332679,20.862800,21.419621,21.996456,22.541440,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.606712,7.926604,8.309896,8.704591,9.106640,9.480804,9.903209,10.288154,NaN,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,39.052626,39.321068,39.649534,39.968299,40.354628,40.723805,41.026351,41.289974,NaN,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.742043,50.667516,52.598171,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,24.584906,25.375037,26.941984,28.983183,30.909991,32.709837,33.998179,35.240236,36.080572,NaN

In [5]:
print("Dataset Shape:", df.shape)

Dataset Shape: (396970, 70)

In [6]:
print("\nColumn Names:")
print(df.columns.tolist())

Column Names:
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 396970 entries, 0 to 396969
Data columns (total 70 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Country Name    396970 non-null  str
 1   Country Code    396970 non-null  str
 2   Indicator Name  396970 non-null  str
 3   Indicator Code  396970 non-null  str
 4   1960            37226 non-null   float64
 5   1961            42560 non-null   float64
 6   1962            43847 non-null   float64
 7   1963            44777 non-null   float64
 8   1964            45283 non-null   float64
 9   1965            47096 non-null   float64
 10  1966            47354 non-null   float64
 11  1967            47991 non-null   float64
 12  1968            48608 non-null   float64
 13  1969            49391 non-null   float64
 14  1970            72137 non-null   float64
 15  1971            76468 non-null   float64
 16  1972            78158 non-null   float64
 17  1973            78812 non-null   float64
 18  1974            80261 non-null   float64
 19  1975            83745 non-null   float64
 20  1976            86075 non-null   float64
 21  1977            88559 non-null   float64
 22  1978            89343 non-null   float64
 23  1979            90276 non-null   float64
 24  1980            94123 non-null   float64
 25  1981            96243 non-null   float64
 26  1982            96543 non-null   float64
 27  1983            97493 non-null   float64
 28  1984            98193 non-null   float64
 29  1985            100174 non-null  float64
 30  1986            101149 non-null  float64
 31  1987            101574 non-null  float64
 32  1988            100997 non-null  float64
 33  1989            102599 non-null  float64
 34  1990            128978 non-null  float64
 35  1991            136638 non-null  float64
 36  1992            139780 non-null  float64
 37  1993            142430 non-null  float64
 38  1994            144761 non-null  float64
 39  1995            151520 non-null  float64
 40  1996            154570 non-null  float64
 41  1997            152610 non-null  float64
 42  1998            157533 non-null  float64
 43  1999            161452 non-null  float64
 44  2000            193690 non-null  float64
 45  2001            186622 non-null  float64
 46  2002            191542 non-null  float64
 47  2003            192210 non-null  float64
 48  2004            195435 non-null  float64
 49  2005            205865 non-null  float64
 50  2006            207580 non-null  float64
 51  2007            210176 non-null  float64
 52  2008            210075 non-null  float64
 53  2009            213019 non-null  float64
 54  2010            223453 non-null  float64
 55  2011            219703 non-null  float64
 56  2012            221107 non-null  float64
 57  2013            219907 non-null  float64
 58  2014            225363 non-null  float64
 59  2015            229580 non-null  float64
 60  2016            225445 non-null  float64
 61  2017            223337 non-null  float64
 62  2018            222457 non-null  float64
 63  2019            219545 non-null  float64
 64  2020            217006 non-null  float64
 65  2021            211473 non-null  float64
 66  2022            197996 non-null  float64
 67  2023            184172 non-null  float64
 68  2024            150158 non-null  float64
 69  2025            81671 non-null   float64
dtypes: float64(66), str(4)
memory usage: 212.0 MB

In [8]:
df.isnull().sum()

Country Name           0
Country Code           0
Indicator Name         0
Indicator Code         0
1960              359744
                   ...
2021              185497
2022              198974
2023              212798
2024              246812
2025              315299
Length: 70, dtype: int64

In [9]:
internet_indicators = df[df["Indicator Name"].str.contains("internet", case=False, na=False)]

internet_indicators["Indicator Name"].unique()

<StringArray>
[               'Individuals using the Internet (% of population)',
 'Individuals using the Internet, female (% of female population)',
     'Individuals using the Internet, male (% of male population)',
                                         'Secure Internet servers',
                  'Secure Internet servers (per 1 million people)']
Length: 5, dtype: str

In [10]:
selected_indicators = [
    "Individuals using the Internet (% of population)",
    "Individuals using the Internet, female (% of female population)",
    "Individuals using the Internet, male (% of male population)",
    "Secure Internet servers (per 1 million people)"
]

filtered_df = df[df["Indicator Name"].isin(selected_indicators)]

filtered_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
662,Africa Eastern and Southern,AFE,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.300000,17.300000,19.600000,21.600000,23.500000,25.000000,26.800000,27.80000,28.800000,30.4
663,Africa Eastern and Southern,AFE,"Individuals using the Internet, female (% of f...",IT.NET.USER.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,18.400000,20.000000,21.900000,23.800000,24.80000,25.600000,NaN
664,Africa Eastern and Southern,AFE,"Individuals using the Internet, male (% of mal...",IT.NET.USER.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,24.900000,26.200000,28.200000,29.800000,30.90000,32.000000,NaN
1307,Africa Eastern and Southern,AFE,Secure Internet servers (per 1 million people),IT.NET.SECR.P6,NaN,NaN,NaN,NaN,NaN,NaN,...,92.922431,875.511831,1138.515909,1291.533036,1277.717594,1436.913526,1332.877133,1307.54868,1472.151483,NaN
2160,Africa Western and Central,AFW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,20.900000,23.800000,25.700000,28.500000,31.500000,34.700000,37.500000,38.50000,40.000000,42.4

In [11]:
filtered_df.shape

(1060, 70)

In [12]:
filtered_df["Country Code"].str.len().value_counts()

Country Code
3    1060
Name: count, dtype: int64

In [13]:
sorted(filtered_df["Country Name"].unique())

['Afghanistan',
 'Africa Eastern and Southern',
 'Africa Western and Central',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Antigua and Barbuda',
 'Arab World',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas, The',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei Darussalam',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Caribbean small states',
 'Cayman Islands',
 'Central African Republic',
 'Central Europe and the Baltics',
 'Chad',
 'Channel Islands',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo, Dem. Rep.',
 'Congo, Rep.',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czechia',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Early-demographic dividend',
 'East Asia & Pacific',
 'East Asia & Pacific (IDA & IBRD countries)',
 'East Asia & Pacific (excluding high income)',
 'Ecuador',
 'Egypt, Arab Rep.',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Euro area',
 'Europe & Central Asia',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Europe & Central Asia (excluding high income)',
 'European Union',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Polynesia',
 'Gabon',
 'Gambia, The',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Heavily indebted poor countries (HIPC)',
 'High income',
 'Honduras',
 'Hong Kong SAR, China',
 'Hungary',
 'IBRD only',
 'IDA & IBRD total',
 'IDA blend',
 'IDA only',
 'IDA total',
 'Iceland',
 'India',
 'Indonesia',
 'Iran, Islamic Rep.',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 "Korea, Dem. People's Rep.",
 'Korea, Rep.',
 'Kosovo',
 'Kuwait',
 'Kyrgyz Republic',
 'Lao PDR',
 'Late-demographic dividend',
 'Latin America & Caribbean',
 'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Latvia',
 'Least developed countries: UN classification',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Low & middle income',
 'Low income',
 'Lower middle income',
 'Luxembourg',
 'Macao SAR, China',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Micronesia, Fed. Sts.',
 'Middle East, North Africa, Afghanistan & Pakistan',
 'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
 'Middle income',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Naoero',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North America',
 'North Macedonia',
 'Northern Mariana Islands',
 'Norway',
 'Not classified',
 'OECD members',
 'Oman',
 'Other small states',
 'Pacific island small states',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Post-demographic dividend',
 'Pre-demographic dividend',
 'Puerto Rico (US)',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten (Dutch part)',
 'Slovak Republic',
 'Slovenia',
 'Small states',
 'Solomon Islands',
 'Somalia, Fed. Rep.',
 'South Africa',
 'South Asia',
 'South Asia (IDA & IBRD)',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'St. Kitts and Nevis',
 'St. Lucia',
 'St. Martin (French part)',
 'St. Vincent and the Grenadines',
 'Sub-Saharan Africa',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Sub-Saharan Africa (excluding high income)',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syrian Arab Republic',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkiye',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Upper middle income',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela, RB',
 'Viet Nam',
 'Virgin Islands (U.S.)',
 'West Bank and Gaza',
 'World',
 'Yemen, Rep.',
 'Zambia',
 'Zimbabwe']

In [14]:
filtered_df["Country Name"].nunique()

265

In [15]:
filtered_df["Country Name"].unique()[:30]

<StringArray>
[                         'Africa Eastern and Southern',
                           'Africa Western and Central',
                                           'Arab World',
                               'Caribbean small states',
                       'Central Europe and the Baltics',
                           'Early-demographic dividend',
                                  'East Asia & Pacific',
          'East Asia & Pacific (excluding high income)',
           'East Asia & Pacific (IDA & IBRD countries)',
                                            'Euro area',
                                'Europe & Central Asia',
        'Europe & Central Asia (excluding high income)',
         'Europe & Central Asia (IDA & IBRD countries)',
                                       'European Union',
               'Heavily indebted poor countries (HIPC)',
                                          'High income',
                                            'IBRD only',
                                     'IDA & IBRD total',
                                            'IDA blend',
                                             'IDA only',
                                            'IDA total',
                            'Late-demographic dividend',
                            'Latin America & Caribbean',
    'Latin America & Caribbean (excluding high income)',
 'Latin America & the Caribbean (IDA & IBRD countries)',
         'Least developed countries: UN classification',
                                  'Low & middle income',
                                           'Low income',
                                  'Lower middle income',
    'Middle East, North Africa, Afghanistan & Pakistan']
Length: 30, dtype: str

In [16]:
selected_countries = [
    "Nigeria",
    "United States",
    "United Kingdom",
    "China",
    "India",
    "Japan",
    "Brazil",
    "South Africa",
    "Germany",
    "Canada"
]

country_df = filtered_df[filtered_df["Country Name"].isin(selected_countries)]

country_df.shape

(40, 70)

In [17]:
long_df = country_df.melt(
    id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
    var_name="Year",
    value_name="Value"
)

long_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value
0,Brazil,BRA,Individuals using the Internet (% of population),IT.NET.USER.ZS,1960,NaN
1,Brazil,BRA,"Individuals using the Internet, female (% of f...",IT.NET.USER.FE.ZS,1960,NaN
2,Brazil,BRA,"Individuals using the Internet, male (% of mal...",IT.NET.USER.MA.ZS,1960,NaN
3,Brazil,BRA,Secure Internet servers (per 1 million people),IT.NET.SECR.P6,1960,NaN
4,Canada,CAN,Individuals using the Internet (% of population),IT.NET.USER.ZS,1960,NaN

In [18]:
long_df.shape

(2640, 6)

In [19]:
long_df["Year"] = long_df["Year"].astype(int)

long_df.dtypes

Country Name          str
Country Code          str
Indicator Name        str
Indicator Code        str
Year                int64
Value             float64
dtype: object

In [20]:
# Remove rows with missing values
clean_df = long_df.dropna(subset=["Value"])

# Check the new shape
clean_df.shape

(674, 6)

In [21]:
clean_df.to_csv(
    r"C:\Users\HomePC\Desktop\Week 8 AnalystLab\Cleaned_Internet_Indicators.csv",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!

In [22]:
clean_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value
1200,Brazil,BRA,Individuals using the Internet (% of population),IT.NET.USER.ZS,1990,0.000
1204,Canada,CAN,Individuals using the Internet (% of population),IT.NET.USER.ZS,1990,0.361
1208,China,CHN,Individuals using the Internet (% of population),IT.NET.USER.ZS,1990,0.000
1212,Germany,DEU,Individuals using the Internet (% of population),IT.NET.USER.ZS,1990,0.126
1216,India,IND,Individuals using the Internet (% of population),IT.NET.USER.ZS,1990,0.000

In [23]:
internet_users = clean_df[
    clean_df["Indicator Name"] == "Individuals using the Internet (% of population)"
]

internet_users.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value
1200,Brazil,BRA,Individuals using the Internet (% of population),IT.NET.USER.ZS,1990,0.000
1204,Canada,CAN,Individuals using the Internet (% of population),IT.NET.USER.ZS,1990,0.361
1208,China,CHN,Individuals using the Internet (% of population),IT.NET.USER.ZS,1990,0.000
1212,Germany,DEU,Individuals using the Internet (% of population),IT.NET.USER.ZS,1990,0.126
1216,India,IND,Individuals using the Internet (% of population),IT.NET.USER.ZS,1990,0.000

In [24]:
internet_users.shape

(344, 6)

In [25]:
average_internet = (
    internet_users.groupby("Country Name")["Value"]
    .mean()
    .sort_values(ascending=False)
)

average_internet

Country Name
Canada            60.525894
United Kingdom    58.591178
United States     57.331950
Germany           55.856558
Japan             55.447719
Brazil            33.988180
China             32.315975
South Africa      27.335539
India             14.943503
Nigeria           14.497139
Name: Value, dtype: float64